### ISSUE TITLE
Add `create_fish_db()` to tests so the tests can access the data and run correctly

### ISSUE THREAD

**Issue by sbashevkin** [Delta-Stewardship-Council/deltafish#1]
A few things to consider for this:
1) How do we ensure the `create_fish_db` test runs first?
2) Will this take too long to run on github actions for it to be feasible? Would we want to cache the database so it is not re-downloaded for each github actions check?

**Comment by jeanetteclark** [comment]
done in https://github.com/Delta-Stewardship-Council/deltafish/commit/68fdcac711fe636da80110512b63d703fd907993, however the windows check is still failing because of memory issues

**Comment by jeanetteclark** [comment]
Closing since we are passing on all platforms now
