### ISSUE TITLE
`Date` and `Datetime` columns are formatted as characters

### ISSUE THREAD

**Issue by sbashevkin** [Delta-Stewardship-Council/deltafish#10]
Can we format these columns as date and datetimes? Do Arrow/duckdb support those?

**Comment by jeanetteclark** [comment]
this was implemented, Sam is checking about time zones

**Comment by sbashevkin** [comment]
I added timezones in https://github.com/Delta-Stewardship-Council/deltafish/commit/dac48872c44d349596a6aeab17c85c766ade6a36 so I think we can close this
