### ISSUE TITLE
Add option to `create_fish_db()` to select the EDI version you wish to download

### ISSUE THREAD

**Issue by sbashevkin** [Delta-Stewardship-Council/deltafish#5]
It would be great to not only implement automatic version checking, but also enable users to select the specific EDI version they wish to download if they wish to work off a specific version.

**Comment by jeanetteclark** [comment]
can check `EDIutils` for this, package id is EDI 1075, https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=1075&revision=1
