### ISSUE TITLE
ensure test coverage in `deltafish` mirrors that of `LTMRdata` where appropriate

### ISSUE THREAD

**Issue by jeanetteclark** [Delta-Stewardship-Council/deltafish#7]
existing LTMR tests

https://docs.google.com/spreadsheets/d/1ayfoYHu_uW93t-gUev2XsVz4p5kgBryjoeyIRsEUV8I/edit#gid=0

**Comment by sbashevkin** [comment]
I think we're pretty close to being done on this. The only outstanding issue I see is that the [coverage report](https://app.codecov.io/gh/Delta-Stewardship-Council/deltafish?branch=main) is showing some gaps, mainly in the `stop` error checking within our functions, so we might want to add some tests for the failing cases. We should also probably test `clear_cache` but would need to make sure that runs after all the other tests are run.

**Comment by jeanetteclark** [comment]
I implemented testing on clear_cache, and added some other tests to increase our coverage (we are at 90% now). I think we are ready to close this one - thoughts @sbashevkin?
